apiVersion: 1

datasources:
  - name: JSON API
    type: marcusolsson-json-datasource
    access: proxy
    orgId: 1
    isDefault: true
    editable: true
    url: http://json-server:5001
    jsonData:
      httpMethod: GET
